import type { Metadata } from "next";
import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Headder";  
import PageTransition from "@/components/PageTransition";
import Staireffct from "@/components/Staireffct";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const jetBrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-jetbrains-mono",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"]
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${jetBrainsMono.variable} antialiased`}>
      <Header/>
      <Staireffct/>
      <PageTransition>{children}</PageTransition>
      </body>
    </html>
  );
}
